edtlib: fix possible AttributeError in Property.description
Attempting to access the property Property.description
when Property.spec.description is None would raise
AttributeError: 'NoneType' object has no attribute 'strip'.

Known affected properties:
+ 'compatible' for nodes such as / /soc /soc/timer@e000e010 /leds /pwmleds
+ 'reg'        for nodes such as /soc/timer@e000e010
+ 'status'     for nodes such as /soc/timer@e000e010
+ 'gpios'      for nodes such as /leds/led_0 /buttons/button_0
+ 'pwms'       for nodes such as /pwmleds/pwm_led_0

We should check the PropertySpec.description attribute before calling strip().